Initialise archive file name in all code paths
Variable fname will stay uninitialised if the sample has no name. This
will lead to an exception further down when the local file name is
constructed for extraction:

[ERROR] karton.archive-extractor: Failed to process task - 4900d4bd-13d7-406e-b7f3-e2f195b63769
Traceback (most recent call last):
  File "/opt/karton-archive-extractor/lib/python3.8/site-packages/karton/core/karton.py", line 178, in internal_process
self.process(self.current_task)
  File "/opt/karton-archive-extractor/lib/python3.8/site-packages/karton/archive_extractor/archive_extractor.py", line 58, in process
    filepath = f"{dir_name}/{fname}"
UnboundLocalError: local variable 'fname' referenced before assignment

This can be avoided by initialising the variable name beforehand so it
is always initialised and only overridden in the case that a sample name
is at hand.

Signed-off-by: Michael Weiser <michael.weiser@gmx.de>